### ISSUE TITLE
How to uninstall the iTypeScript kernel?

### ISSUE THREAD

**Issue by dclong** [nearbydelta/itypescript#11]
Is there any command to uninstall the iTypeScript kernel?

**Comment by nearbydelta** [comment]
You can remove the kernel using Jupyter Notebook command [reference: StackOverflow](https://stackoverflow.com/questions/42635310/remove-kernel-on-jupyter-notebook):
```
jupyter kernelspec uninstall typescript
```

If you also want to remove globally installed iTypescript npm package, then type:
```
npm uninstall -g itypescript
```

**Comment by dclong** [comment]
Thank you, @nearbydelta!
