### ISSUE TITLE
$TS is not defined

### ISSUE THREAD

**Issue by BartNetJS** [nearbydelta/itypescript#5]
Hi

I'm following the [sample here]( https://nearbydelta.github.io/itypescript/doc/graphics.ipynb.html)
But got $TS is not defined when I try to execute $TS.log("hello, world!");

I'm I missing something?

**Comment by nearbydelta** [comment]
Sorry for the late reply.
I found that the sample code is not correctly written. I updated and checked the validity of the code, for the newest version of ITypescript (0.3.0).
